descriptions:
  - dataType: "perf"
    modalityLabel: "asl"
    criteria:
      ProtocolName: "ep2d_pasl"
      MagneticFieldStrength: 3
      MRAcquisitionType: "2D"
      ImageType:
        [
          "ORIGINAL",
          "PRIMARY",
          "ASL",
          "NONE",
          "ND",
          "NORM",
          "FILTERED",
          "MOSAIC",
        ]
    sidecarChanges":
      ArterialSpinLabelingType: "PASL"
      PostLabelingDelay: 1.8
      BackgroundSuppression: false
      M0Type: "Included"
      TotalAcquiredPairs: 54
      AcquisitionVoxelSize: [3.5, 3.5, 4.5]
      BolusCutOffFlag: true
      BolusCutOffDelayTime: 0.7
      BolusCutOffTechnique: "Q2TIPS"
      PASLType: "PICORE"
    aslContext:
      [
        "m0scan",
        "control",
        "label",
        "control",
        "label",
        "control",
        "label",
        "control",
        "label",
        "control",
        "label",
        "control",
        "label",
        "control",
        "label",
        "control",
        "label",
        "control",
        "label",
        "control",
        "label",
        "control",
        "label",
        "control",
        "label",
        "control",
        "label",
        "control",
        "label",
        "control",
        "label",
        "control",
        "label",
        "control",
        "label",
        "control",
        "label",
        "control",
        "label",
        "control",
        "label",
        "control",
        "label",
        "control",
        "label",
        "control",
        "label",
        "control",
        "label",
        "control",
        "label",
        "control",
        "label",
        "control",
        "label",
        "control",
        "label",
        "control",
        "label",
        "control",
        "label",
        "control",
        "label",
        "control",
        "label",
        "control",
        "label",
        "control",
        "label",
        "control",
        "label",
        "control",
        "label",
        "control",
        "label",
        "control",
        "label",
        "control",
        "label",
        "control",
        "label",
        "control",
        "label",
        "control",
        "label",
        "control",
        "label",
        "control",
        "label",
        "control",
        "label",
        "control",
        "label",
        "control",
        "label",
        "control",
        "label",
        "control",
        "label",
        "control",
        "label",
        "control",
        "label",
        "control",
        "label",
        "control",
        "label",
        "control",
        "label",
      ]
